name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Publish Extension (Code Marketplace, release)
        run: npx vsce publish --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
